context.modules = [
    {
        name = libpipewire-module-echo-cancel
        args = {
            aec.method = webrtc
            node.latency = 1024/48000
            source.props = {
                node.name        = "echo-cancel-source"
                node.description = "Echo-Cancel Source"
                audio.rate       = 48000
            }
            sink.props = {
                node.name        = "echo-cancel-sink"
                node.description = "Echo-Cancel Sink"
                audio.rate       = 48000
            }
        }
    }
]
