context.modules = [
    { name = libpipewire-module-echo-cancel
      args = {
          monitor.mode = true
          node.latency = 1024/48000
          aec.method = "webrtc"
          aec.args = {
              "webrtc.gain_control" = false
              "webrtc.noise_suppression" = true
          }
          source.props = {
              node.name = "echo-cancel-source"
              node.description = "Echo-Cancel Source"
              audio.rate = 48000
          }
      }
    }
]
