general {
    lock_cmd = pidof hyprlock || hyprlock                                                          # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                                       # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r    # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 90                             # 1.5 minutes.   
    on-timeout = brightnessctl -s set 10     # set backlight to minimum, avoid 0 to turn on OLED monitor.    
    on-resume = brightnessctl -r                 
}

listener {
    timeout = 180                            # 3 minutes.
    on-timeout = loginctl lock-session       # lock pc when timeout has passed.     
}

listener {
    timeout = 240                                # 4 minutes.                    
    on-timeout = hyprctl dispatch dpms off       # screen off when timeout has passed.                     
    on-resume = hyprctl dispatch dpms on         # screen on when activity is detected press any key or move mouse. 
}

listener {
    timeout = 300                           # 5 minutes.
    on-timeout = systemctl suspend          # suspend pc.      
}
